molpro_path: "/home/trushin/Molpro-dev/molpro-swap/bin/"
partition: "mem256"
create_runsh: True
output_dir: "RAW_OUTPUTS/KSINV_ROHF"
systems: ["B", "C", "N", "O", "F", "Al", "Si", "P", "S", "Cl"]
calc_type: "KSINV"
reference: "ROHF"
mb_methods: ["RS2", "CISD", "AQCC"]
plot: False
